# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'selfCateringCafe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'SDCycleScrollView'
  pod 'MJRefresh' 
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'
  pod 'YYKit'
  pod 'DZNEmptyDataSet'  
 # Pods for selfCateringCafe

end
